### PR TITLE
Update to use the new string representation of a Multihash.

### PR DESCRIPTION
**Pull request by kevina**
Factored out of #47

### CODE REVIEW

**Comment by kevina** [comment]
@Stebalien can you have a look at this.  This change needs to go in if we are going to update to the string representation of a multihash.  It also has a few other optimizations in.

**Comment by kevina** [comment]
Note: This is based on #71.  Please approve but don't merge.  It has a gx-depenecy on a non-pinned hash that I will get ride of once https://github.com/multiformats/go-multihash/pull/84 is merged.

**Comment by ribasushi** [comment]
@Stebalien is this still relevant? Seems everything has already migrated to strings...

**Comment by Stebalien** [comment]
The goal was to _also_ migrate multihash.

**Pull request closed without merging**
