### PR TITLE
Expose panic in Cast()

### PR DESCRIPTION
**Pull request by lgierth**
Not sure exactly how to fix it yet, but I though I'd write it down for general entertainment.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@lgierth the only way i see this happening is if theres a race condition. How are you reproducing the panic?

binary.Uvarint won't return a value past the length of the buffer.

**Comment by lgierth** [comment]
`while true; do go test . ; done` crashes 100 % of the runs

**Comment by lgierth** [comment]
It starts crashing for some `500 < i < 1000`

**Comment by lgierth** [comment]
Taken care of in #7

**Pull request closed without merging**
