### PR TITLE
default cidv1 to base32

### PR DESCRIPTION
**Pull request by Stebalien**
https://github.com/ipfs/go-ipfs/issues/6220

### CODE REVIEW

**Comment by Stebalien** [comment]
@whyrusleeping or @anorth,

We'd like to make go-cid return base32 CIDv1 CIDs by default instead of base58 (CIDv0 CIDs will continue to use base58). The argument is that:

1. Not many users are using CIDv1 yet so this shouldn't be to obvious of a change.
2. We'd like to switch to base32 by default eventually as it's case-insensitive. There's no reason not to switch now.

Proposal here: https://github.com/ipfs/go-ipfs/issues/6220

---

As far as I can tell, the go-filecoin project doesn't test against any hard-coded base32 CIDv1 CIDs so this shouldn't have any impact (other than maybe changing the CLI output in some cases). However, I figured you'd like to be aware of this change and have a chance to raise objections.

If you _do_ have any repos with a bunch of base58 CIDv1 CIDs that you'd like to convert, the following perl script works pretty well (but double check the results, it has false positives):

```
perl -i -e 'sub base32 { my ($cid) = @_; my $res=`ipfs cid base32 $cid`; chomp $res; return $res; }' -pe 's/\b(z[a-zA-Z0-9]{10,})/"@{[base32($1)]}"/ge' **/*
```

**Comment by whyrusleeping** [comment]
SGTM, ship it!

**Comment by anorth** [comment]
No objections, thanks for the heads-up!

**Comment by Stebalien** [comment]
@lidel I fixed the readme but couldn't find the CIDs you're referring to in the tests.

**Comment by hsanjuan** [comment]
Heads up: breaking change tagged with patch release. People may rely on what cid strings look like (for me it just breaks sharness tests).

**Comment by Stebalien** [comment]
Apologies, I should have bumped the minor.

**Pull request merged**
